version: '3.8'

services:
  api.dssid:
    image: dssid/whatsapp-web-api:latest
    networks:
      - dssiditexperts
    volumes:
    - api.dssid_sessions:/usr/src/app/sessions
    environment:
      - API_KEY=dssiditexperts  # OPTIONAL
      - BASE_WEBHOOK_URL=https://dssiditexperts.com/localCallbackExample
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION
      - MAX_ATTACHMENT_SIZE=5000000 # IN BYTES
      - SET_MESSAGES_AS_SEEN=TRUE # WILL MARK THE MESSAGES AS READ AUTOMATICALLY
      # ALL CALLBACKS: auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed
      - DISABLED_CALLBACKS=message_ack  # PREVENT SENDING CERTAIN TYPES OF CALLBACKS BACK TO THE WEBHOOK
      - ENABLE_SWAGGER_ENDPOINT=TRUE # OPTIONAL, ENABLES THE /api-docs ENDPOINT
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.dssid.rule=Host(`https://dssiditexperts.com`)
        - traefik.http.routers.api.dssid.entrypoints=websecure
        - traefik.http.routers.api.dssid.tls.certresolver=letsencryptresolver
        - traefik.http.routers.api.dssid.priority=1
        - traefik.http.routers.api.dssid.service=api.dssid
        - traefik.http.services.api.dssid.loadbalancer.server.port=3000
        - traefik.http.services.api.dssid.loadbalancer.passHostHeader=true

volumes:
  api.dssid_sessions:
    external: true
    name: api.dssid_sessions

networks:
  dssiditexperts:
    name: dssiditexperts
    external: true
